---
name: test1

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.7

      - name: Prepare environment
        run: |
          bundle config set --local without 'system_tests'
          bundle install
          git config --global user.name test1.github-action
          git config --global user.email test1.github-action@users.noreply.github.com

      - name: Update GH-Pages
        run: bundle exec rake strings:gh_pages:update
