---
name: test1

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.7

      - name: Prepare environment
        run: |
          bundle config set --local without 'system_tests'
          bundle install
          git config --global user.name ${{ github.actor }}
          git config --global user.email rtib@users.noreply.github.com

      - name: Update Reference.md
        run: bundle exec rake strings:generate:reference

      - name: Update Changelog.md
        run: bundle exec rake changelog

      - name: Check for changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Commit changes
        if: steps.changes.outputs.changed == 1
        run: |
          git add .
          git commit -m "auto strings:generate:reference"
          git push

#      - name: Update GH-Pages
#        run: bundle exec rake strings:gh_pages:update
