---
name: test1

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.7

      - name: Prepare environment
        run: |
          bundle config set --local without 'system_tests'
          bundle install

      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Update GH-Pages
        run: bundle exec rake strings:gh_pages:update
