---
name: test1

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.7

      - name: Prepare environment
        run: |
          bundle config set --local without 'system_tests'
          bundle install

      - name: Update Reference.md
        run: |
          bundle exec rake strings:generate:reference
          git config user.name ${{ github.actor }}
          git config user.email rtib@users.noreply.github.com
          git add .
          git commit -m "auto strings:generate:reference"
          git push
